apiVersion: v2
name: prospectml
description: A Helm chart for ProspectML - AI-powered coding agent
type: application
version: 0.0.2-test.3
appVersion: "1.0.0"
keywords:
  - ai
  - machine-learning
  - coding-agent
  - flask
home: https://github.com/AlgorithmicResearchGroup/Coding-Agent-For-Deployment
sources:
  - https://github.com/AlgorithmicResearchGroup/Coding-Agent-For-Deployment
maintainers:
  - name: ProspectML Team
    email: info@algorithmicresearchgroup.com
dependencies:
  - name: postgresql
    version: "13.2.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: minio
    version: 17.0.11
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: minio.enabled
