apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prospectml.fullname" . }}
  labels:
    {{- include "prospectml.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prospectml.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prospectml.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prospectml.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
            successThreshold: {{ .Values.healthcheck.successThreshold }}
            failureThreshold: {{ .Values.healthcheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
            successThreshold: {{ .Values.healthcheck.successThreshold }}
            failureThreshold: {{ .Values.healthcheck.failureThreshold }}
          {{- end }}
          env:         
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | default "" | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "prospectml.fullname" . }}
            - secretRef: 
                name: {{ include "prospectml.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range $index, $config := .Values.volumeClaim.claims }}
            - name: {{ $config.name }}
              mountPath: {{ $config.mountPath }}
            {{- end }}
      volumes:
        {{- range $index, $config := .Values.volumeClaim.claims }}
        - name: {{ $config.name }}
          {{- if eq $.Values.volumeClaim.type "emptydir" }}
          emptyDir:
            sizeLimit: {{ $config.size }}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ $.Chart.Name }}-{{ $config.name }}
          {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}