apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prospectml.fullname" . }}
  labels:
    {{- include "prospectml.labels" . | nindent 4 }}
type: Opaque
data:
  # Flask secret key
  SECRET_KEY: {{ .Values.flask.secretKey | b64enc | quote }}
  
  # Database password
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else if .Values.database.external.enabled }}
  POSTGRES_PASSWORD: {{ .Values.database.external.password | b64enc | quote }}
  {{- end }}
  
  # AI Provider API Keys
  {{- if .Values.aiProviders.anthropic.apiKey }}
  ANTHROPIC_API_KEY: {{ .Values.aiProviders.anthropic.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.aiProviders.openai.apiKey }}
  OPENAI_API_KEY: {{ .Values.aiProviders.openai.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.aiProviders.google.apiKey }}
  GOOGLE_API_KEY: {{ .Values.aiProviders.google.apiKey | b64enc | quote }}
  {{- end }}
  
  # AWS Credentials
  {{- if .Values.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc | quote }}
  {{- end }}
  
  # WANDB API Key
  {{- if .Values.wandb.apiKey }}
  WANDB_API_KEY: {{ .Values.wandb.apiKey | b64enc | quote }}
  {{- end }}

  # License Key
  {{- if .Values.license.Key }}
  License_KEY: {{ .Values.license.Key | b64enc | quote }}
  {{- end }}