name: Release Helm Chart

on:
  workflow_run:
    workflows: ["Generate Helm Docs"]
    branches:
      - main
    types:
      - completed

jobs:
  release:
    name: Release Chart
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install -g semantic-release @semantic-release/exec @semantic-release/git @semantic-release/github
          sudo snap install yq || true

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release || echo "No release"
      
      - name: Check if Semantic Release published
        id: release-check
        run: |
          if [ -f .version ]; then
            echo "Published version: $(cat .version)"
            echo "published=true" >> $GITHUB_OUTPUT
          else
            echo "No new version published."
            echo "published=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm chart
        if: steps.release-check.outputs.published == 'true'
        run: |
          mkdir -p .cr-release-packages
          helm dependency update .
          helm package . -d .cr-release-packages

      - name: Push to gh-pages
        if: steps.release-check.outputs.published == 'true'
        run: |
          CHART_REPO_DIR=./
          CHART_DIR=.cr-release-packages

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

          mkdir -p $CHART_REPO_DIR

          BRANCH="${GITHUB_REF##*/}"

          if [[ "$BRANCH" == "next" ]]; then
            DEST_DIR="$CHART_REPO_DIR/pre"
            REPO_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/pre"
          else
            DEST_DIR="$CHART_REPO_DIR"
            REPO_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}"
          fi

          mkdir -p "$DEST_DIR"
          cp $CHART_DIR/*.tgz "$DEST_DIR"

          helm repo index "$DEST_DIR" --url "$REPO_URL"

          git add "$DEST_DIR"
          git commit -m "Publish Helm chart from $BRANCH $(date)" || echo "No changes to commit"
          git push origin gh-pages
